export type ProgressStatus = "blue" | "yellow" | "red" | "green" | "none"

export interface AutonomousIndicator {
  id: string
  category: string
  indicatorName: string
  programName: string
  baseValue: string
  target2025: string
  current2025: string
  achievementRate: string
  achievementPercent: number
  progress: ProgressStatus
  target2026: string
  target2027: string
}

export const indicators: AutonomousIndicator[] = [
  {
    id: "1-1-1",
    category: "교육과정",
    indicatorName: "대학원 차원의 Core Curriculum 개선",
    programName: "대학원 전체 대상의 일반공통 Core Curriculum 교육과정 운영(운영 과목 수)",
    baseValue: "10",
    target2025: "12",
    current2025: "6",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "14",
    target2027: "16",
  },
  {
    id: "1-1-2",
    category: "교육과정",
    indicatorName: "대학원 차원의 Core Curriculum 개선",
    programName: "UN SDGs 연계 교육과정 확대 운영 (적용 교과목 수)",
    baseValue: "87",
    target2025: "100",
    current2025: "66",
    achievementRate: "66%",
    achievementPercent: 66,
    progress: "blue",
    target2026: "120",
    target2027: "140",
  },
  {
    id: "1-1-4",
    category: "교육과정",
    indicatorName: "역량기반 전공교육 시행",
    programName: "핵심역량 기반 교육 체계 구축",
    baseValue: "신규",
    target2025: "제도마련",
    current2025: "검토",
    achievementRate: "60%",
    achievementPercent: 60,
    progress: "none",
    target2026: "시행",
    target2027: "-",
  },
  {
    id: "1-1-5",
    category: "교육과정",
    indicatorName: "역량기반 비교과 프로그램 활성화",
    programName: "[TOTAL] 대학원생 연구역량 강화 프로그램 개설 운영(만족도)",
    baseValue: "신규",
    target2025: "4",
    current2025: "1",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "4.2",
    target2027: "4.3",
  },
  {
    id: "1-2-1",
    category: "학사관리",
    indicatorName: "학사관리 시스템 개선",
    programName: "혁신 교수법 적용 (SEMO Class, PBL, Living Lab 등 교과목 수)",
    baseValue: "41",
    target2025: "45",
    current2025: "25",
    achievementRate: "56%",
    achievementPercent: 56,
    progress: "blue",
    target2026: "50",
    target2027: "55",
  },
  {
    id: "1-2-2",
    category: "학사관리",
    indicatorName: "학사관리 시스템 개선",
    programName: "[TOTAL] KUSEUM 대학원생 교과,비교과 통합이력 관리 시스템 구축",
    baseValue: "신규",
    target2025: "구축",
    current2025: "진행중",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "yellow",
    target2026: "시행",
    target2027: "-",
  },
  {
    id: "1-3-1",
    category: "교육지원체계",
    indicatorName: "학습지원 프로그램",
    programName: "[TOTAL] 학습역량강화 프로그램 개발 (Academic Advisory, 학술저성과자 프로그램)(만족도)",
    baseValue: "신규",
    target2025: "4",
    current2025: "기획중",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "4.2",
    target2027: "4.3",
  },
  {
    id: "1-3-2",
    category: "교육지원체계",
    indicatorName: "우수 대학원생 확보",
    programName: "우수 대학원생 확보를 위한 장학금 확대",
    baseValue: "시행",
    target2025: "10",
    current2025: "-",
    achievementRate: "60%",
    achievementPercent: 60,
    progress: "blue",
    target2026: "10",
    target2027: "11",
  },
  {
    id: "1-4-1",
    category: "경력개발 및 복지 증진 지원",
    indicatorName: "경력개발지원",
    programName: "[TOTAL] 진로 및 경력개발 프로그램 (만족도)",
    baseValue: "신규",
    target2025: "4",
    current2025: "-",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "4.2",
    target2027: "4.3",
  },
  {
    id: "1-4-2",
    category: "경력개발 및 복지 증진 지원",
    indicatorName: "경력개발지원",
    programName: "[TOTAL] 대학원생 진로개발 적성검사 실시 (만족도)",
    baseValue: "신규",
    target2025: "4",
    current2025: "-",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "1-5-1",
    category: "경력개발 및 복지 증진 지원",
    indicatorName: "복지 증진/권익 보호",
    programName: "모성 보호를 위한 제도 개선 및 운영",
    baseValue: "신규",
    target2025: "제도마련",
    current2025: "구축",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "red",
    target2026: "시행",
    target2027: "-",
  },
  {
    id: "1-5-2",
    category: "경력개발 및 복지 증진 지원",
    indicatorName: "복지 증진/권익 보호",
    programName: "대학원생 민원 개선 (민원 처리 만족도)",
    baseValue: "신규",
    target2025: "4",
    current2025: "-",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "blue",
    target2026: "4.2",
    target2027: "4.3",
  },
  {
    id: "1-6-1",
    category: "대학원 AI 전환",
    indicatorName: "대학원생 AI 활용 기회 제공",
    programName: "일반공통 Core-Curriculum 내 AI 관련 교과목 신설 개발",
    baseValue: "신규",
    target2025: "1",
    current2025: "진행중",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "-",
    target2027: "시행",
  },
  {
    id: "1-6-2",
    category: "대학원 AI 전환",
    indicatorName: "대학원생 AI 활용 기회 제공",
    programName: "생성형 AI Tool 사용 지원 사업",
    baseValue: "신규",
    target2025: "제도마련",
    current2025: "진행중",
    achievementRate: "0.3%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "시행",
    target2027: "-",
  },
  {
    id: "2-1-1",
    category: "연구지원",
    indicatorName: "연구역량 향상 지원체계",
    programName: "우수 교원 유치를 위한 제도 개선",
    baseValue: "신규",
    target2025: "개선안",
    current2025: "논의중",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "2-1-2",
    category: "연구지원",
    indicatorName: "연구역량 향상 지원체계",
    programName: "우수 교원 지원제도 (책임수업시수 감면, 특별연구비 지급 제도, 정년 후 교원 임용 등)",
    baseValue: "신규",
    target2025: "-",
    current2025: "제도마련",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "시행",
    target2027: "-",
  },
  {
    id: "2-2-1",
    category: "연구지원",
    indicatorName: "학생중심 연구지원체계",
    programName: "[TOTAL] 대학원생 연구 활성화 지원사업",
    baseValue: "4",
    target2025: "4",
    current2025: "2",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "4.2",
    target2027: "4.3",
  },
  {
    id: "2-2-2",
    category: "연구지원",
    indicatorName: "학생중심 연구지원체계",
    programName: "연구 성과 펠로우십 장학금",
    baseValue: "신규",
    target2025: "0.6억",
    current2025: "시행",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "2-3-1",
    category: "연구지원",
    indicatorName: "연구자 중심 연구지원 체계 개선",
    programName: "[공통] 전문학술지 논문 게재 지원 건수",
    baseValue: "개편",
    target2025: "개편안",
    current2025: "진행중",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "-",
    target2027: "시행",
  },
  {
    id: "2-3-2",
    category: "연구지원",
    indicatorName: "연구자 중심 연구지원 체계 개선",
    programName: "[공통] 국제학술지 게재예정 논문 원문교정 지원 건수",
    baseValue: "개편",
    target2025: "개편",
    current2025: "진행중",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "3-1-1",
    category: "산학협력 플랫폼",
    indicatorName: "연구자 중심 산학협력 플랫폼 구축",
    programName: "산학협력 프로그램 (SEMO Class 배움나눔형 교과목) 개발 및 운영",
    baseValue: "신규",
    target2025: "2",
    current2025: "4",
    achievementRate: "200%",
    achievementPercent: 200,
    progress: "green",
    target2026: "3",
    target2027: "4",
  },
  {
    id: "3-1-2",
    category: "산학협력 플랫폼",
    indicatorName: "연구자 중심 산학협력 플랫폼 구축",
    programName: "주문식 교육과정 운영 (계약학과 및 활용과정 등)",
    baseValue: "-",
    target2025: "1",
    current2025: "4",
    achievementRate: "400%",
    achievementPercent: 400,
    progress: "blue",
    target2026: "1",
    target2027: "1",
  },
  {
    id: "3-2-1",
    category: "산학협력 플랫폼",
    indicatorName: "산업계 및 지역사회 참여 촉진",
    programName: "지역공헌위원회 운영",
    baseValue: "2",
    target2025: "2",
    current2025: "1",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "2",
    target2027: "2",
  },
  {
    id: "3-2-2",
    category: "산학협력 플랫폼",
    indicatorName: "산업 및 지역사회 참여 촉진",
    programName: "가족회사 중심 인턴십/현장실습 지원",
    baseValue: "신규",
    target2025: "기획",
    current2025: "진행중",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "3-3-1",
    category: "산학협력 플랫폼",
    indicatorName: "기술사업화 및 창업 지원",
    programName: "[산단] 기술사업화 지원체계 고도화",
    baseValue: "신규",
    target2025: "고도화",
    current2025: "진행중",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "3-3-4",
    category: "산학협력 플랫폼",
    indicatorName: "기술사업화 및 창업 지원",
    programName: "교원 창업, 실험실 창업 지원제도 정비",
    baseValue: "신규",
    target2025: "정비",
    current2025: "진행중",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "4-1-1",
    category: "국제화 플랫폼",
    indicatorName: "국제 공동연구 지원",
    programName: "스마트시티 연구 관련 국제화 플랫폼 구축 (국제교류 파트 신설, 전담인력 채용 등)",
    baseValue: "신규",
    target2025: "구성",
    current2025: "완료",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "red",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "4-1-2",
    category: "국제화 플랫폼",
    indicatorName: "국제 공동연구 지원",
    programName: "신남방연구센터를 활용 글로벌 네트워크 강화 (공동연구 및 교류활동 지원)",
    baseValue: "신규",
    target2025: "과제수",
    current2025: "0",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "1",
    target2027: "1",
  },
  {
    id: "4-2-1",
    category: "국제화 플랫폼",
    indicatorName: "해외 우수 대학원생 유치",
    programName: "외국인 대상 Offer Package (입학 및 생활 지원) 제도 도입",
    baseValue: "신규",
    target2025: "제도마련",
    current2025: "기획중",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "4-2-2",
    category: "국제화 플랫폼",
    indicatorName: "해외 우수 대학원생 유치",
    programName: "우수 해외 대학원생 유치 확대 (기획 및 홍보물품 강화)",
    baseValue: "신규",
    target2025: "벤치마킹",
    current2025: "기획중",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "4-3-1",
    category: "국제화 플랫폼",
    indicatorName: "국제 교류 지원",
    programName: "국제통하계학교/대학원생 국제교육 프로그램 지원 (서울 공통)",
    baseValue: "신규",
    target2025: "지원",
    current2025: "지원",
    achievementRate: "0%",
    achievementPercent: 0,
    progress: "red",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "4-3-2",
    category: "국제화 플랫폼",
    indicatorName: "국제 교류 지원",
    programName: "해외 우수대학과의 복수학위 협약을 위한 행정지원",
    baseValue: "-",
    target2025: "지원",
    current2025: "지원",
    achievementRate: "0%",
    achievementPercent: 0,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "5-1-1",
    category: "비전 및 목표",
    indicatorName: "중장기 계획,비전 및 목표 수립",
    programName: "국제경쟁력을 갖춘 연구중심대학 비전 및 목표 수립",
    baseValue: "수립",
    target2025: "-",
    current2025: "-",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "5-2-1",
    category: "성과관리",
    indicatorName: "본부 중심 성과관리 체계 구축",
    programName: "대학원 중심의 거버넌스 확립 : 대학원 조직 개편",
    baseValue: "개편",
    target2025: "-",
    current2025: "-",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "5-2-2",
    category: "성과관리",
    indicatorName: "본부 중심 성과관리 체계 구축",
    programName: "대학원 중심의 거버넌스 확립 : 대학원 조직 개편",
    baseValue: "신규",
    target2025: "-",
    current2025: "-",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "5-3-1",
    category: "성과관리",
    indicatorName: "성과 확산",
    programName: "성과 및 연구자 홍보 체계 개선(연구자 프로파일 제작 수)",
    baseValue: "신규",
    target2025: "50",
    current2025: "47",
    achievementRate: "94%",
    achievementPercent: 94,
    progress: "blue",
    target2026: "100",
    target2027: "150",
  },
  {
    id: "5-3-2",
    category: "성과관리",
    indicatorName: "성과 확산",
    programName: "우수 사례 발굴 및 홍보 강화(언론 기사화 건수)",
    baseValue: "신규",
    target2025: "20",
    current2025: "19",
    achievementRate: "95%",
    achievementPercent: 95,
    progress: "blue",
    target2026: "30",
    target2027: "40",
  },
  {
    id: "5-4-1",
    category: "교직원 실무역량 강화",
    indicatorName: "교직원 실무역량 강화",
    programName: "BK21 현장전문인력 기능 강화 (직무역량 향상 과정) (만족도)",
    baseValue: "신규",
    target2025: "4",
    current2025: "-",
    achievementRate: "50%",
    achievementPercent: 50,
    progress: "blue",
    target2026: "4.2",
    target2027: "4.3",
  },
  {
    id: "5-4-2",
    category: "교직원 실무역량 강화",
    indicatorName: "교직원 실무역량 강화",
    programName: "대학혁신 실무협의회(교육연구단팀) 구성 및 밑단 강화",
    baseValue: "신규",
    target2025: "구성",
    current2025: "구성",
    achievementRate: "100%",
    achievementPercent: 100,
    progress: "blue",
    target2026: "-",
    target2027: "-",
  },
  {
    id: "5-5-1",
    category: "인력양성사업과 R&D사업간 연계",
    indicatorName: "인력양성사업 및 R&D사업간 연계를 통한 시너지 창출",
    programName: "대학혁신지원사업 등 부 재정지원사업간 연계한 대학원생 지원",
    baseValue: "신규",
    target2025: "스크리닝",
    current2025: "-",
    achievementRate: "30%",
    achievementPercent: 30,
    progress: "blue",
    target2026: "스크리닝",
    target2027: "스크리닝",
  },
  {
    id: "5-5-2",
    category: "인력양성사업과 R&D사업간 연계",
    indicatorName: "인력양성사업 및 R&D사업간 연계를 통한 시너지 창출",
    programName: "BK21 사업 간접비를 활용한 다양한 교내 연구 지원 제도 보조",
    baseValue: "신규",
    target2025: "스크리닝",
    current2025: "-",
    achievementRate: "-",
    achievementPercent: 0,
    progress: "blue",
    target2026: "스크리닝",
    target2027: "스크리닝",
  },
]

export const categoryOrder = [
  "교육과정",
  "학사관리",
  "교육지원체계",
  "경력개발 및 복지 증진 지원",
  "대학원 AI 전환",
  "연구지원",
  "산학협력 플랫폼",
  "국제화 플랫폼",
  "비전 및 목표",
  "성과관리",
  "교직원 실무역량 강화",
  "인력양성사업과 R&D사업간 연계",
]

export const categoryColors: Record<string, string> = {
  "교육과정": "#7E191B",
  "학사관리": "#9C2A2C",
  "교육지원체계": "#B23A3C",
  "경력개발 및 복지 증진 지원": "#C86A6C",
  "대학원 AI 전환": "#2563EB",
  "연구지원": "#16A34A",
  "산학협력 플랫폼": "#D97706",
  "국제화 플랫폼": "#7C3AED",
  "비전 및 목표": "#0891B2",
  "성과관리": "#4F46E5",
  "교직원 실무역량 강화": "#DB2777",
  "인력양성사업과 R&D사업간 연계": "#64748B",
}

export function getCategoryStats() {
  const stats: Record<string, { count: number; totalAchievement: number; items: AutonomousIndicator[] }> = {}

  for (const cat of categoryOrder) {
    stats[cat] = { count: 0, totalAchievement: 0, items: [] }
  }

  for (const ind of indicators) {
    if (!stats[ind.category]) {
      stats[ind.category] = { count: 0, totalAchievement: 0, items: [] }
    }
    stats[ind.category].count++
    stats[ind.category].totalAchievement += Math.min(ind.achievementPercent, 100)
    stats[ind.category].items.push(ind)
  }

  return stats
}

export function getProgressCounts() {
  const counts = { blue: 0, yellow: 0, red: 0, green: 0, none: 0 }
  for (const ind of indicators) {
    counts[ind.progress]++
  }
  return counts
}

export function getOverallStats() {
  const total = indicators.length
  const achieved = indicators.filter((i) => i.achievementPercent >= 100).length
  const inProgress = indicators.filter((i) => i.achievementPercent > 0 && i.achievementPercent < 100).length
  const notStarted = indicators.filter((i) => i.achievementPercent === 0).length
  const avgAchievement = Math.round(
    indicators.reduce((sum, i) => sum + Math.min(i.achievementPercent, 100), 0) / total
  )

  return { total, achieved, inProgress, notStarted, avgAchievement }
}
