export type FieldType = "교육" | "연구" | "산학협력" | "국제화"
export type IndicatorType = "결과" | "과정" | "투입" | "-"

export interface CoreSubIndicator {
  id: string
  code: string
  type: IndicatorType
  name: string
  formula: string
  source: string
  target24: string
  target25Goal: string
  target26: string
  target27Goal: string
  current25: string
  achievement25: string
  isParent?: boolean
}

export interface CoreField {
  field: FieldType
  color: string
  bgColor: string
  borderColor: string
  indicators: CoreSubIndicator[]
}

export const coreFields: CoreField[] = [
  {
    field: "교육",
    color: "#DC2626",
    bgColor: "#FEF2F2",
    borderColor: "#FECACA",
    indicators: [
      {
        id: "E1",
        code: "E1",
        type: "-",
        name: "신입생/재학생 충원율",
        formula: "(0.7\u00D7E1a)+(0.3\u00D7E1b)",
        source: "-",
        target24: "89.1%",
        target25Goal: "92.6%",
        target26: "96.2%",
        target27Goal: "100.0%",
        current25: "105.5%",
        achievement25: "113.9%",
        isParent: true,
      },
      {
        id: "E1a",
        code: "E1a",
        type: "결과",
        name: "신입생 충원율",
        formula: "(당해 정원 내 입학자수 / 당해 정원 내 모집인원)\u00D7100(%)",
        source: "정보 공시",
        target24: "84.8%",
        target25Goal: "89.7%",
        target26: "94.7%",
        target27Goal: "100.0%",
        current25: "108.5%",
        achievement25: "121.0%",
      },
      {
        id: "E1b",
        code: "E1b",
        type: "결과",
        name: "재학생 충원율",
        formula: "(당해 대학원 지원자 / 당해 입학정원)\u00D7100(%)",
        source: "정보 공시",
        target24: "99.2%",
        target25Goal: "99.4%",
        target26: "99.7%",
        target27Goal: "100.0%",
        current25: "98.5%",
        achievement25: "99.0%",
      },
      {
        id: "E2",
        code: "E2",
        type: "-",
        name: "교육과정 혁신지수",
        formula: "(0.2\u00D7E2a)+(0.2\u00D7E2b)+(0.2\u00D7E2c)+(0.2\u00D7E2d)+(0.2\u00D7E2e)",
        source: "-",
        target24: "62.2%",
        target25Goal: "73.3%",
        target26: "85.8%",
        target27Goal: "100.0%",
        current25: "82.0%",
        achievement25: "111.9%",
        isParent: true,
      },
      {
        id: "E2a",
        code: "E2a",
        type: "투입",
        name: "학석사 연계과정 수",
        formula: "당해년도 학석사 연계과정 수",
        source: "부서 수합",
        target24: "23",
        target25Goal: "25",
        target26: "28",
        target27Goal: "31",
        current25: "22",
        achievement25: "86.6%",
      },
      {
        id: "E2b",
        code: "E2b",
        type: "투입",
        name: "석박사 통합과정 수",
        formula: "당해년도 석박사 연계과정 수",
        source: "부서 수합",
        target24: "20",
        target25Goal: "22",
        target26: "24",
        target27Goal: "27",
        current25: "17",
        achievement25: "77.3%",
      },
      {
        id: "E2c",
        code: "E2c",
        type: "과정",
        name: "Core-Curriculum 교양 교육과정 운영 수",
        formula: "당해년도 운영 중 C\u00B7C 교양과목 수",
        source: "AMS",
        target24: "3",
        target25Goal: "4",
        target26: "5",
        target27Goal: "6",
        current25: "3",
        achievement25: "75.0%",
      },
      {
        id: "E2d",
        code: "E2d",
        type: "과정",
        name: "Core-Curriculum 전공 교육과정 운영 수",
        formula: "당해년도 운영 중 C\u00B7C 전공과목 수",
        source: "AMS",
        target24: "7",
        target25Goal: "8",
        target26: "9",
        target27Goal: "10",
        current25: "7",
        achievement25: "87.5%",
      },
      {
        id: "E2e",
        code: "E2e",
        type: "과정",
        name: "전문 역량 강화 프로그램 참여 학생 수",
        formula: "당해년도 전문 역량 강화 프로그램 참여 학생 수",
        source: "부서 수합",
        target24: "183",
        target25Goal: "245",
        target26: "333",
        target27Goal: "450",
        current25: "696",
        achievement25: "284.1%",
      },
      {
        id: "E3",
        code: "E3",
        type: "-",
        name: "연구인재 배출지수",
        formula: "(0.2\u00D7E3a)+(0.2\u00D7E3b)+(0.2\u00D7E3c)+(0.2\u00D7E3d)+(0.2\u00D7E3e)",
        source: "-",
        target24: "43.8%",
        target25Goal: "53.8%",
        target26: "85.8%",
        target27Goal: "100.0%",
        current25: "68.3%",
        achievement25: "127.0%",
        isParent: true,
      },
      {
        id: "E3a",
        code: "E3a",
        type: "결과",
        name: "외국대학 임용 지수",
        formula: "해외 대학 교원 임용 건수\u00D71.5",
        source: "부서 수합",
        target24: "0.0",
        target25Goal: "0.0",
        target26: "1.5",
        target27Goal: "1.0",
        current25: "1.5",
        achievement25: "150.0%",
      },
      {
        id: "E3b",
        code: "E3b",
        type: "결과",
        name: "해외 저명 연구소 취업 지수",
        formula: "해외 저명 연구소 취업 건수\u00D71.2",
        source: "부서 수합",
        target24: "1.2",
        target25Goal: "1.2",
        target26: "1.2",
        target27Goal: "2.0",
        current25: "1.2",
        achievement25: "98.1%",
      },
      {
        id: "E3c",
        code: "E3c",
        type: "결과",
        name: "국내 대학 교원 임용 지수",
        formula: "국내 대학 교원 임용 건수\u00D71.2",
        source: "부서 수합",
        target24: "2.4",
        target25Goal: "3.6",
        target26: "3.6",
        target27Goal: "4.0",
        current25: "0",
        achievement25: "0.0%",
      },
      {
        id: "E3d",
        code: "E3d",
        type: "결과",
        name: "국내 국책 연구소 취업 지수",
        formula: "국내 국책 연구소 취업 건수",
        source: "부서 수합",
        target24: "2",
        target25Goal: "3",
        target26: "4",
        target27Goal: "8",
        current25: "6",
        achievement25: "200.0%",
      },
      {
        id: "E3e",
        code: "E3e",
        type: "결과",
        name: "국내 산업체 연구소 취업 지수",
        formula: "국내 산업체 연구소 취업 건수",
        source: "부서 수합",
        target24: "22",
        target25Goal: "24",
        target26: "26",
        target27Goal: "30",
        current25: "17",
        achievement25: "71.4%",
      },
    ],
  },
  {
    field: "연구",
    color: "#16A34A",
    bgColor: "#F0FDF4",
    borderColor: "#BBF7D0",
    indicators: [
      {
        id: "R1",
        code: "R1",
        type: "-",
        name: "실용연구력 향상지수",
        formula: "(0.4\u00D7R1a)+(0.3\u00D7R1b)+(0.3\u00D7R1c)",
        source: "-",
        target24: "82.7%",
        target25Goal: "88.0%",
        target26: "93.8%",
        target27Goal: "100.0%",
        current25: "89.3%",
        achievement25: "101.4%",
        isParent: true,
      },
      {
        id: "R1a",
        code: "R1a",
        type: "결과",
        name: "교원 1인당 논문 피인용 지수",
        formula: "전년도 교원 1인당 논문 피인용 지수",
        source: "SciVal",
        target24: "3.9",
        target25Goal: "4.06",
        target26: "4.27",
        target27Goal: "4.5",
        current25: "4.13",
        achievement25: "101.7%",
      },
      {
        id: "R1b",
        code: "R1b",
        type: "결과",
        name: "1인당 SCI급 논문 수",
        formula: "전년도 교원 1인당 SCI급 이상 논문 수",
        source: "RMS",
        target24: "0.43",
        target25Goal: "0.45",
        target26: "0.48",
        target27Goal: "0.50",
        current25: "0.50",
        achievement25: "110.0%",
      },
      {
        id: "R1c",
        code: "R1c",
        type: "결과",
        name: "대외 연구비 수주액",
        formula: "전년도 교외 연구비 수주 총액 (단위: 천억원)",
        source: "정보 공시",
        target24: "0.35",
        target25Goal: "0.39",
        target26: "0.43",
        target27Goal: "0.47",
        current25: "0.36",
        achievement25: "91.6%",
      },
      {
        id: "R2",
        code: "R2",
        type: "-",
        name: "연구역량 향상지수",
        formula: "(0.4\u00D7R2a)+(0.3\u00D7R2b)+(0.3\u00D7R2c)",
        source: "-",
        target24: "73.8%",
        target25Goal: "78.1%",
        target26: "95.7%",
        target27Goal: "100.0%",
        current25: "74.4%",
        achievement25: "95.2%",
        isParent: true,
      },
      {
        id: "R2a",
        code: "R2a",
        type: "과정",
        name: "책임시수 감면 건수",
        formula: "당해년도 책임시수 감면 및 연간책임시수제 시행 건수",
        source: "부서 수합",
        target24: "3",
        target25Goal: "3",
        target26: "4",
        target27Goal: "4",
        current25: "2",
        achievement25: "66.7%",
      },
      {
        id: "R2b",
        code: "R2b",
        type: "과정",
        name: "성과 중심 연구 인센티브 지급액",
        formula: "당해년도 성과 중심 연구 인센티브 지급 총액 (단위 : 억원)",
        source: "연구산학처",
        target24: "5",
        target25Goal: "5",
        target26: "6",
        target27Goal: "6",
        current25: "4.05",
        achievement25: "80.8%",
      },
      {
        id: "R2c",
        code: "R2c",
        type: "과정",
        name: "연구트랙제도 해당 교원 수",
        formula: "당해년도 연구트랙제도 참여 교원 수",
        source: "연구산학처",
        target24: "19",
        target25Goal: "22",
        target26: "25",
        target27Goal: "29",
        current25: "33",
        achievement25: "148.0%",
      },
    ],
  },
  {
    field: "산학협력",
    color: "#D97706",
    bgColor: "#FFFBEB",
    borderColor: "#FDE68A",
    indicators: [
      {
        id: "C1",
        code: "C1",
        type: "-",
        name: "산학협력 활성화 지수",
        formula: "(0.25\u00D7C1a)+(0.25\u00D7C1b)+(0.25\u00D7C1c)+(0.25\u00D7C1d)",
        source: "-",
        target24: "61.9%",
        target25Goal: "73.0%",
        target26: "85.9%",
        target27Goal: "100.0%",
        current25: "0.0%",
        achievement25: "0.0%",
        isParent: true,
      },
      {
        id: "C1a",
        code: "C1a",
        type: "결과",
        name: "협력기관 수",
        formula: "당해년도 기준 관, 학, 연, 업 등 협력기관 수 누계",
        source: "부서수합",
        target24: "103",
        target25Goal: "118",
        target26: "136",
        target27Goal: "150",
        current25: "",
        achievement25: "0.0%",
      },
      {
        id: "C1b",
        code: "C1b",
        type: "과정",
        name: "산학협력 프로그램 수",
        formula: "당해년도 기준 산학협력 프로그램 수 누계",
        source: "AMS",
        target24: "80",
        target25Goal: "96",
        target26: "115",
        target27Goal: "138",
        current25: "",
        achievement25: "0.0%",
      },
      {
        id: "C1c",
        code: "C1c",
        type: "과정",
        name: "계약학과 및 협동과정 개설 수",
        formula: "당해년도 계약학과 및 협동과정 개설 수",
        source: "부서 수합",
        target24: "7",
        target25Goal: "8",
        target26: "9",
        target27Goal: "10",
        current25: "",
        achievement25: "0.0%",
      },
      {
        id: "C1d",
        code: "C1d",
        type: "결과",
        name: "기술사업화 건수",
        formula: "당해년도 발생 기술사업화 건수",
        source: "부서 수합",
        target24: "10",
        target25Goal: "13",
        target26: "16",
        target27Goal: "20",
        current25: "",
        achievement25: "0.0%",
      },
      {
        id: "C2",
        code: "C2",
        type: "과정",
        name: "사회문제해결 교과목 개설 건수",
        formula: "사회문제해결 교과목 개설 건수",
        source: "부서 수합",
        target24: "68",
        target25Goal: "73",
        target26: "78",
        target27Goal: "85",
        current25: "",
        achievement25: "0.0%",
        isParent: true,
      },
    ],
  },
  {
    field: "국제화",
    color: "#7C3AED",
    bgColor: "#F5F3FF",
    borderColor: "#DDD6FE",
    indicators: [
      {
        id: "I1",
        code: "I1",
        type: "-",
        name: "국제 공동 연구 건수",
        formula: "(0.5\u00D7I1a)+(0.5\u00D7I1b)",
        source: "-",
        target24: "96.6%",
        target25Goal: "97.7%",
        target26: "98.9%",
        target27Goal: "100.0%",
        current25: "114.9%",
        achievement25: "117.6%",
        isParent: true,
      },
      {
        id: "I1a",
        code: "I1a",
        type: "결과",
        name: "5개년 국제논문 FWCI",
        formula: "최근 5년간 국제논문 FWCI 합 / 전체 논문 수",
        source: "SciVal",
        target24: "1.13",
        target25Goal: "1.14",
        target26: "1.15",
        target27Goal: "1.16",
        current25: "1.24",
        achievement25: "108.8%",
      },
      {
        id: "I1b",
        code: "I1b",
        type: "결과",
        name: "전년도 국제 연구 협력국가 수",
        formula: "전년도 국제연구 협력국가 수",
        source: "SciVal",
        target24: "33",
        target25Goal: "34",
        target26: "34",
        target27Goal: "35",
        current25: "43",
        achievement25: "126.5%",
      },
      {
        id: "I2",
        code: "I2",
        type: "-",
        name: "국제화 지수",
        formula: "(0.25\u00D7I2a)+(0.25\u00D7I2b)+(0.25\u00D7I2c)+(0.25\u00D7I2d)",
        source: "-",
        target24: "74.6%",
        target25Goal: "78.2%",
        target26: "96.4%",
        target27Goal: "100.0%",
        current25: "71.3%",
        achievement25: "91.2%",
        isParent: true,
      },
      {
        id: "I2a",
        code: "I2a",
        type: "결과",
        name: "외국인 교원 수",
        formula: "당해년도 외국인 교원 수",
        source: "정보 공시",
        target24: "18",
        target25Goal: "18",
        target26: "19",
        target27Goal: "19",
        current25: "19",
        achievement25: "105.6%",
      },
      {
        id: "I2b",
        code: "I2b",
        type: "결과",
        name: "외국인 유학생 수",
        formula: "당해년도 외국인 유학생 수",
        source: "정보 공시",
        target24: "56",
        target25Goal: "58",
        target26: "60",
        target27Goal: "62",
        current25: "58",
        achievement25: "100.0%",
      },
      {
        id: "I2c",
        code: "I2c",
        type: "투입",
        name: "해외대학 복수학위 확대 건수",
        formula: "당해년도 해외대학 복수학위 협정 체결 수",
        source: "부서 수합",
        target24: "1",
        target25Goal: "1",
        target26: "2",
        target27Goal: "2",
        current25: "0",
        achievement25: "0.0%",
      },
      {
        id: "I2d",
        code: "I2d",
        type: "과정",
        name: "연구협력 네트워킹 활동 건 수",
        formula: "당해년도 국제학회, 단/장기 방문연구 등 활동 건수",
        source: "부서 수합",
        target24: "38",
        target25Goal: "45",
        target26: "53",
        target27Goal: "60",
        current25: "55",
        achievement25: "123.0%",
      },
      {
        id: "I3",
        code: "I3",
        type: "결과",
        name: "외국인 유학생 증가율",
        formula: "당해년도 외국인 유학생 증가 수 / 전년도 외국인 유학생 총수",
        source: "정보 공시",
        target24: "10",
        target25Goal: "10",
        target26: "15",
        target27Goal: "15",
        current25: "20",
        achievement25: "200.0%",
        isParent: true,
      },
    ],
  },
]

// Helper functions
export function getFieldStats() {
  return coreFields.map((f) => {
    const parentIndicators = f.indicators.filter((i) => i.isParent)
    const achievementValues = parentIndicators
      .map((i) => parseFloat(i.achievement25))
      .filter((v) => !isNaN(v))
    const avgAchievement =
      achievementValues.length > 0
        ? Math.round(achievementValues.reduce((a, b) => a + b, 0) / achievementValues.length)
        : 0

    return {
      field: f.field,
      color: f.color,
      bgColor: f.bgColor,
      borderColor: f.borderColor,
      totalIndicators: f.indicators.length,
      parentCount: parentIndicators.length,
      avgAchievement,
    }
  })
}

export function getOverallCoreStats() {
  const allParents = coreFields.flatMap((f) =>
    f.indicators.filter((i) => i.isParent)
  )
  const achievementValues = allParents
    .map((i) => parseFloat(i.achievement25))
    .filter((v) => !isNaN(v))
  const totalIndicators = coreFields.reduce(
    (sum, f) => sum + f.indicators.length,
    0
  )
  const avgAchievement =
    achievementValues.length > 0
      ? Math.round(
          achievementValues.reduce((a, b) => a + b, 0) / achievementValues.length
        )
      : 0

  const achieved = achievementValues.filter((v) => v >= 100).length
  const inProgress = achievementValues.filter((v) => v > 0 && v < 100).length
  const notStarted = achievementValues.filter((v) => v === 0).length

  return {
    totalIndicators,
    parentCount: allParents.length,
    avgAchievement,
    achieved,
    inProgress,
    notStarted,
  }
}
